#!/bin/bash
# Format work items output as CSV or Markdown
# Reads: work-items.json
# Outputs: work-items.{csv|md} based on FORMAT
#
# Required env vars:
#   FORMAT - Output format: json, csv, markdown
#
# Optional env vars:
#   PROJECT_NAME - For report header
#   SPRINT - For report header

set -e

FORMAT="${FORMAT:-json}"
PROJECT="${PROJECT_NAME:-}"
SPRINT_NAME="${SPRINT:-}"

COUNT=$(cat work-items.json | jq '. | length')

if [ "$COUNT" -eq 0 ]; then
  echo "No work items found"
  echo "[]" > "work-items.$FORMAT"
  exit 0
fi

case "$FORMAT" in
  csv)
    {
      echo "ID,Title,State,AssignedTo,Iteration,Area,Priority,StoryPoints,Tags,Created,Modified"
      cat work-items.json | jq -r '.[] | [
        .fields["System.Id"] // "",
        (.fields["System.Title"] // "" | gsub(","; " ") | gsub("\""; "")),
        .fields["System.State"] // "",
        (.fields["System.AssignedTo"].displayName // "Unassigned"),
        .fields["System.IterationPath"] // "",
        .fields["System.AreaPath"] // "",
        (.fields["Microsoft.VSTS.Common.Priority"] // "" | tostring),
        (.fields["Microsoft.VSTS.Scheduling.StoryPoints"] // "" | tostring),
        (.fields["System.Tags"] // "" | gsub(","; ";")),
        .fields["System.CreatedDate"] // "",
        .fields["System.ChangedDate"] // ""
      ] | @csv'
    } > work-items.csv
    echo "Generated work-items.csv with $COUNT items"
    ;;

  markdown|md)
    {
      echo "# Work Items Report"
      echo ""
      echo "| Field | Value |"
      echo "|-------|-------|"
      echo "| Generated | $(date -u +"%Y-%m-%d %H:%M UTC") |"
      [ -n "$PROJECT" ] && echo "| Project | $PROJECT |"
      [ -n "$SPRINT_NAME" ] && echo "| Sprint | $SPRINT_NAME |"
      echo "| Count | $COUNT |"
      echo ""
      echo "## Items"
      echo ""
      echo "| ID | Title | State | Assigned To | Priority | Points |"
      echo "|---:|-------|-------|-------------|:--------:|-------:|"

      cat work-items.json | jq -r '.[] |
        "| \(.fields["System.Id"]) | \(.fields["System.Title"] // "-" | .[0:50] | gsub("\\|"; "-")) | \(.fields["System.State"] // "-") | \(.fields["System.AssignedTo"].displayName // "Unassigned") | \(.fields["Microsoft.VSTS.Common.Priority"] // "-") | \(.fields["Microsoft.VSTS.Scheduling.StoryPoints"] // "-") |"'

      echo ""
      echo "---"
      echo "*Generated by Azure DevOps Pipeline*"
    } > work-items.md
    echo "Generated work-items.md with $COUNT items"
    ;;

  json|*)
    echo "Using work-items.json with $COUNT items"
    ;;
esac
